name: build-container-group

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta (linux)
        id: meta-linux
        uses: docker/metadata-action@v4
        with:
          images: milran/some-container
          bake-target: docker-metadata-action-linux
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            prefix=linux-
      -
        name: Docker meta (nanoserver)
        id: meta-nanoserver
        uses: docker/metadata-action@v4
        with:
          images: milran/some-container
          bake-target: docker-metadata-action-nanoserver
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            prefix=nanoserver-
      - name: Merge buildx bake files
        run: |
            jq -s '.[0] * .[1]' ${{ steps.meta-linux.outputs.bake-file }} ${{ steps.meta-nanoserver.outputs.bake-file }} > docker-bake.override.json
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          files: |
            another-container-group/docker-bake.hcl
            docker-bake.override.json
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max